# Generated by Django 3.0.6 on 2020-05-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(max_length=1000)),
                ('mes', models.CharField(max_length=100000)),
            ],
        ),
    ]
