# Generated by Django 3.0.6 on 2020-05-26 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Send_Email', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email_model',
            options={'get_latest_by': 'id'},
        ),
    ]
