# Generated by Django 3.0.6 on 2020-05-26 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Send_Email', '0002_auto_20200526_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_model',
            name='mes',
            field=models.CharField(max_length=10000000000000000),
        ),
        migrations.AlterField(
            model_name='email_model',
            name='sub',
            field=models.CharField(max_length=10000000),
        ),
    ]
