# Generated by Django 3.0.6 on 2020-05-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Send_Email', '0003_auto_20200526_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('from_mail', models.EmailField(max_length=300)),
                ('to_mail', models.EmailField(max_length=300)),
            ],
        ),
    ]
