# Generated by Django 3.0.6 on 2020-05-27 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Send_Email', '0004_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='time',
        ),
    ]
