# Generated by Django 3.0.6 on 2020-05-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Send_Email', '0005_remove_users_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='attachments',
            field=models.FileField(blank=True, upload_to='documents'),
        ),
    ]
