# Generated by Django 3.0.6 on 2020-05-28 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Send_Email', '0006_users_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='attachments',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
    ]
