# Generated by Django 3.0.6 on 2020-05-29 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Send_Email', '0007_auto_20200528_1321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'users', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='users',
            name='attachments',
            field=models.FileField(blank=True, upload_to='doc/'),
        ),
    ]
