# Generated by Django 3.0.6 on 2020-05-29 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Send_Email', '0008_auto_20200529_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='attachments',
        ),
    ]
