# Generated by Django 3.0.6 on 2020-05-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Send_Email', '0009_remove_users_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_model',
            name='mes',
            field=models.CharField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='email_model',
            name='sub',
            field=models.CharField(max_length=10000),
        ),
    ]
