# Generated by Django 3.0.6 on 2020-05-31 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Send_Email', '0010_auto_20200531_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_model',
            name='mes',
            field=models.TextField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='email_model',
            name='sub',
            field=models.TextField(max_length=10000),
        ),
    ]
